name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: ice4006-week1-test1
      id: ice4006-week1-test1
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 60
        max-score: 100
        setup-command: ''
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        ICE4006-WEEK1-TEST1_RESULTS: "${{steps.ice4006-week1-test1.outputs.result}}"
      with:
        runners: ice4006-week1-test1
